///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/complete.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:53
///

/// Song 'msc_complete' metadata macros
#define msc_complete_address  0xA120
#define msc_complete_size     269
#define msc_complete_end      0xa22c

/// Song 'msc_complete' array declaration
extern void msc_complete[msc_complete_size];
