///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/gameover.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:54
///

/// Song 'msc_gameover' metadata macros
#define msc_gameover_address  0xA04E
#define msc_gameover_size     210
#define msc_gameover_end      0xa11f

/// Song 'msc_gameover' array declaration
extern void msc_gameover[msc_gameover_size];
