///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/menu.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:56
///

/// Song 'msc_menu' metadata macros
#define msc_menu_address  0x9B88
#define msc_menu_size     842
#define msc_menu_end      0x9ed1

/// Song 'msc_menu' array declaration
extern void msc_menu[msc_menu_size];
