///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/select.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:55
///

/// Song 'msc_select' metadata macros
#define msc_select_address  0x9ED2
#define msc_select_size     380
#define msc_select_end      0xa04d

/// Song 'msc_select' array declaration
extern void msc_select[msc_select_size];
