///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/sfx.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:51
///

/// Song 'sfx' metadata macros
#define sfx_address  0x9AE0
#define sfx_size     168
#define sfx_end      0x9b87

/// Song 'sfx' array declaration
extern void sfx[sfx_size];
