///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sound/stage.aks
/// Generation time: mi., 24 de oct. de 2018 19:35:52
///

/// Song 'msc_stage' metadata macros
#define msc_stage_address  0xA22E
#define msc_stage_size     210
#define msc_stage_end      0xa2ff

/// Song 'msc_stage' array declaration
extern void msc_stage[msc_stage_size];
